### ISSUE TITLE
Problems on Android

### ISSUE THREAD

**Issue by jyhjson** [zoffline/zwift-offline#263] opened 2023-10-25 07:04 UTC
When using an Android phone, you need to log in. It always prompts whether the password has been changed. If the password is wrong, you cannot register a new user.

**Comment by fatsbrown** [comment] 2023-10-26 11:48
Unless something changed in a recent update, if you are running zoffline in single player mode (default) any login and password will work on Android. If you enabled multiplayer you need to signup at `https://<zoffline ip>/signup/` then use this account to login.

**Comment by oldnapalm** [comment] 2023-10-31 17:22
Duplicate of #236

**Closed by oldnapalm** 2023-10-31 17:22 UTC
