### ISSUE TITLE
Cannot login from different PC to existing account

### ISSUE THREAD

**Issue by 6Xkljk8Vj7Tk1k4** [zoffline/zwift-offline#106] opened 2020-12-06 15:32 UTC
Hi,

I created fresh profile (profile1) on PC#1 (Windows 10) then do some activities. After that I switched to PC#2 (Windows 10) and successfully login in launcher. However after that following error appears:
![image](https://user-images.githubusercontent.com/754027/101284369-fc983400-37df-11eb-9a14-396cade8e086.png)

And in log file:
```
ERROR:zwift_offline:Exception on /api/profiles/0 [PUT]
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/zwift-offline/zwift_offline.py", line 315, in wrapper
    login_manager._load_user()
  File "/usr/local/lib64/python3.6/site-packages/flask_login/login_manager.py", line 329, in _load_user
    user = self._load_user_from_remember_cookie(cookie)
  File "/usr/local/lib64/python3.6/site-packages/flask_login/login_manager.py", line 366, in _load_user_from_remember_cookie
    user_id = decode_cookie(cookie)
  File "/usr/local/lib64/python3.6/site-packages/flask_login/utils.py", line 57, in decode_cookie
    payload, digest = cookie.rsplit(u'|', 1)
AttributeError: 'NoneType' object has no attribute 'rsplit'
INFO:zoffline:192.168.15.215 - - [2020-12-06 16:19:20] "PUT /api/profiles/0?only-game-fields=true HTTP/1.1" 500 426 0.001539
ERROR:zwift_offline:Exception on /api/users/logout [POST]
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/zwift-offline/zwift_offline.py", line 315, in wrapper
    login_manager._load_user()
  File "/usr/local/lib64/python3.6/site-packages/flask_login/login_manager.py", line 329, in _load_user
    user = self._load_user_from_remember_cookie(cookie)
  File "/usr/local/lib64/python3.6/site-packages/flask_login/login_manager.py", line 366, in _load_user_from_remember_cookie
    user_id = decode_cookie(cookie)
  File "/usr/local/lib64/python3.6/site-packages/flask_login/utils.py", line 57, in decode_cookie
    payload, digest = cookie.rsplit(u'|', 1)
AttributeError: 'NoneType' object has no attribute 'rsplit'
INFO:zoffline:192.168.15.215 - - [2020-12-06 16:19:21] "POST /api/users/logout HTTP/1.1" 500 426 0.001634
```

I'm able to login and do workouts from android on profile1 also I'm able to create new profile on "PC#2", successfully login and do workouts but for profile1 it doesn't work on PC#2.

I'm using sources from: https://github.com/oldnapalm/zwift-offline

**Comment by oldnapalm** [comment] 2020-12-06 19:25
Can you try to logout from PC#1 (in the launcher window) and see if it makes any difference?

Sure you are using the fork and not the mp branch? Did you clone it recently?

**Comment by zoffline** [comment] 2020-12-06 22:56
Is "Remember me" checked when logging on as profile1 on PC#2?

**Comment by 6Xkljk8Vj7Tk1k4** [comment] 2020-12-07 07:20
I tied to logout from PC#1 and then login on PC#2 that doesn't help still can't login.
I did git clone https://github.com/oldnapalm/zwift-offline.
Yes, I checked "Remember me" on PC#1.

**Comment by oldnapalm** [comment] 2020-12-07 12:31
I think this issue is caused by `login_manager.session_protection = None`

Can you test commenting out line 1680 of zwift_offline.py?

**Comment by 6Xkljk8Vj7Tk1k4** [comment] 2020-12-07 14:36
> I think this issue is caused by `login_manager.session_protection = None`
> 
> Can you test commenting out line 1680 of zwift_offline.py?

Unfortunatelly same results...

**Comment by oldnapalm** [comment] 2020-12-07 15:05
Can you test with `login_manager.session_protection = "strong"` or `login_manager.session_protection = "basic"`?

Using "basic" fixed the issue for me (it's the default value so just commenting line 1680 did it). Using "strong" made "remember me" stop working.

Please check if there's any difference in logs. For me there was no exceptions (using Python 3.8.6), just `PUT /api/profiles/0` (which should never happen).

**Comment by 6Xkljk8Vj7Tk1k4** [comment] 2020-12-07 17:51
Is there any cache available that I can remove? Currently I cannot login from PC#1 and PC#2 ("Failed to login, check internet connection") even for newly created account which works fine from android... and there is no difference if I start standalone.py with strong/basic/none in session_protection.

**Comment by oldnapalm** [comment] 2020-12-07 18:37
Maybe the issue is with Android login. I don't have a rooted device so I can't test.

I can confirm the issue happens on Windows if session_protection is set to None. Using "basic" it works fine, I can login from both computers with the same account.

Can you test changing line 1603 to `login_user(user, remember=False)`?

**Comment by 6Xkljk8Vj7Tk1k4** [comment] 2020-12-07 19:43
Looks like the problem was with wrong branch/tag or whatever.... 
When I took tar.gz from here: https://github.com/oldnapalm/zwift-offline/releases/tag/zoffline_1.0.59353 everything works fine that means: create accounts, login from PC#1, PC#2 and from android as well. Moving my original storage works as well. 
So that means my problem is solved.

But there is in deed problem with master repository as this doesn't work at all and can be simply reproduced:
```
[root@minecraft opt]# python3.8 -m venv p38
[root@minecraft opt]# source p38/bin/activate
(p38) [root@minecraft opt]# cd p38/
(p38) [root@minecraft p38]# python --version
Python 3.8.3
(p38) [root@minecraft p38]# pip install flask flask_sqlalchemy flask-login pyjwt gevent protobuf protobuf3_to_dict stravalib cryptography
Collecting flask
  Using cached https://files.pythonhosted.org/packages/f2/28/2a03252dfb9ebf377f40fba6a7841b47083260bf8bd8e737b0c6952df83f/Flask-1.1.2-py2.py3-none-any.whl
Collecting flask_sqlalchemy
  Using cached https://files.pythonhosted.org/packages/af/4b/3dd83c3e2c6e3034b804d971952e0120606506f153990cc56d2d33173b72/Flask_SQLAlchemy-2.4.4-py2.py3-none-any.whl
Collecting flask-login
  Using cached https://files.pythonhosted.org/packages/2b/83/ac5bf3279f969704fc1e63f050c50e10985e50fd340e6069ec7e09df5442/Flask_Login-0.5.0-py2.py3-none-any.whl
Collecting pyjwt
  Using cached https://files.pythonhosted.org/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl
Collecting gevent
  Using cached https://files.pythonhosted.org/packages/d6/d9/278ed49aeb1a90ef20dc8b8fa9082276a97765402d3587753f1283ca8abb/gevent-20.9.0-cp38-cp38-manylinux2010_x86_64.whl
Collecting protobuf
  Using cached https://files.pythonhosted.org/packages/3e/b2/e4099c78e483e7a612d67eeb0c8740ce15cdeba4a0032da121c791f7d352/protobuf-3.14.0-cp38-cp38-manylinux1_x86_64.whl
Collecting protobuf3_to_dict
  Using cached https://files.pythonhosted.org/packages/6b/55/522bb43539fed463275ee803d79851faaebe86d17e7e3dbc89870d0322b9/protobuf3-to-dict-0.1.5.tar.gz
Collecting stravalib
  Using cached https://files.pythonhosted.org/packages/fe/37/9161484786583fe6a038747e9f14555830de4581f025f086697466023ec6/stravalib-0.10.2.tar.gz
Collecting cryptography
  Downloading https://files.pythonhosted.org/packages/4c/a2/6565c5271a79e3c96d7a079053b4d8408a740d4bf365f0f5f244a807bd09/cryptography-3.2.1-cp35-abi3-manylinux2010_x86_64.whl (2.6MB)
     |████████████████████████████████| 2.6MB 12.1MB/s
Collecting Werkzeug>=0.15
  Using cached https://files.pythonhosted.org/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl
Collecting Jinja2>=2.10.1
  Using cached https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl
Collecting click>=5.1
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
Collecting itsdangerous>=0.24
  Using cached https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting SQLAlchemy>=0.8.0
  Using cached https://files.pythonhosted.org/packages/35/6f/0a48334d857c0ac25c49585b533d0f6845ad1853dabb4625239b695f68d3/SQLAlchemy-1.3.20-cp38-cp38-manylinux2010_x86_64.whl
Requirement already satisfied: setuptools in ./lib/python3.8/site-packages (from gevent) (41.6.0)
Collecting greenlet>=0.4.17; platform_python_implementation == "CPython"
  Using cached https://files.pythonhosted.org/packages/da/8d/0e8d2b0a8d9cb78eb822adcb2a00906406c16bf7b7c561f9ebac96f9fc97/greenlet-0.4.17-cp38-cp38-manylinux1_x86_64.whl
Collecting zope.event
  Using cached https://files.pythonhosted.org/packages/9e/85/b45408c64f3b888976f1d5b37eed8d746b8d5729a66a49ec846fda27d371/zope.event-4.5.0-py2.py3-none-any.whl
Collecting zope.interface
  Using cached https://files.pythonhosted.org/packages/b7/ed/44c57577170ee8edd6cc68de7dda6e99d051e1bb969aade99afba07e8b30/zope.interface-5.2.0-cp38-cp38-manylinux2010_x86_64.whl
Collecting six>=1.9
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting arrow
  Using cached https://files.pythonhosted.org/packages/ca/bc/ebc1afb3c54377e128a01024c006f983d03ee124bc52392b78ba98c421b8/arrow-0.17.0-py2.py3-none-any.whl
Collecting requests<3.0dev,>=2.0
  Using cached https://files.pythonhosted.org/packages/39/fc/f91eac5a39a65f75a7adb58eac7fa78871ea9872283fb9c44e6545998134/requests-2.25.0-py2.py3-none-any.whl
Collecting units
  Using cached https://files.pythonhosted.org/packages/33/8c/76112215f71aad89ffecae90dd1e0a681ad8f750df994d4ce1275bca50a2/units-0.07.tar.gz
Collecting pytz
  Using cached https://files.pythonhosted.org/packages/12/f8/ff09af6ff61a3efaad5f61ba5facdf17e7722c4393f7d8a66674d2dbd29f/pytz-2020.4-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8
  Downloading https://files.pythonhosted.org/packages/66/c8/56efb65bd9fff582c84f11bbfe2cf70c6abcaa852e35be45583e823bb59d/cffi-1.14.4-cp38-cp38-manylinux1_x86_64.whl (411kB)
     |████████████████████████████████| 419kB 19.4MB/s
Collecting MarkupSafe>=0.23
  Using cached https://files.pythonhosted.org/packages/4b/20/f6d7648c81cb84815d0be935d5c74cd1cc0239e43eadb1a61062d34b6543/MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl
Collecting python-dateutil>=2.7.0
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting urllib3<1.27,>=1.21.1
  Using cached https://files.pythonhosted.org/packages/f5/71/45d36a8df68f3ebb098d6861b2c017f3d094538c0fb98fa61d4dc43e69b9/urllib3-1.26.2-py2.py3-none-any.whl
Collecting idna<3,>=2.5
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Collecting certifi>=2017.4.17
  Using cached https://files.pythonhosted.org/packages/5e/a0/5f06e1e1d463903cf0c0eebeb751791119ed7a4b3737fdc9a77f1cdfb51f/certifi-2020.12.5-py2.py3-none-any.whl
Collecting chardet<4,>=3.0.2
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting pycparser
  Downloading https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl (112kB)
     |████████████████████████████████| 112kB 24.8MB/s
Installing collected packages: Werkzeug, MarkupSafe, Jinja2, click, itsdangerous, flask, SQLAlchemy, flask-sqlalchemy, flask-login, pyjwt, greenlet, zope.event, zope.interface, gevent, six, protobuf, protobuf3-to-dict, python-dateutil, arrow, urllib3, idna, certifi, chardet, requests, units, pytz, stravalib, pycparser, cffi, cryptography
    Running setup.py install for protobuf3-to-dict ... done
    Running setup.py install for units ... done
    Running setup.py install for stravalib ... done
Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 SQLAlchemy-1.3.20 Werkzeug-1.0.1 arrow-0.17.0 certifi-2020.12.5 cffi-1.14.4 chardet-3.0.4 click-7.1.2 cryptography-3.2.1 flask-1.1.2 flask-login-0.5.0 flask-sqlalchemy-2.4.4 gevent-20.9.0 greenlet-0.4.17 idna-2.10 itsdangerous-1.1.0 protobuf-3.14.0 protobuf3-to-dict-0.1.5 pycparser-2.20 pyjwt-1.7.1 python-dateutil-2.8.1 pytz-2020.4 requests-2.25.0 six-1.15.0 stravalib-0.10.2 units-0.7 urllib3-1.26.2 zope.event-4.5.0 zope.interface-5.2.0
WARNING: You are using pip version 19.3.1; however, version 20.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(p38) [root@minecraft p38]# git clone https://github.com/oldnapalm/zwift-offline
Cloning into 'zwift-offline'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 2208 (delta 22), reused 35 (delta 12), pack-reused 2155
Receiving objects: 100% (2208/2208), 1.91 MiB | 3.89 MiB/s, done.
Resolving deltas: 100% (1272/1272), done.
(p38) [root@minecraft p38]# cd zwift-offline/
(p38) [root@minecraft zwift-offline]# touch storage/multiplayer.txt
(p38) [root@minecraft zwift-offline]# python standalone.py
INFO:zoffline:Server is running.
192.168.15.180 - - [07/Dec/2020 20:26:40] "GET /gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml HTTP/1.1" 200 -
192.168.15.180 - - [07/Dec/2020 20:26:41] "GET /gameassets/Zwift_Updates_Root/Launcher_ver_cur.xml HTTP/1.1" 200 -
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:26:44] "GET /api/auth HTTP/1.1" 200 222 0.000883
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:26:44] "GET /launcher/realms/zwift/protocol/openid-connect/auth?client_id=Game_Launcher&redirect_uri=http:%2F%2Fzwift%2F&login=true&response_type=code HTTP/1.1" 302 386 0.002419
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:26:44] "GET /login/ HTTP/1.1" 200 2770 0.023932
192.168.15.180 - - [07/Dec/2020 20:26:45] "GET /gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml HTTP/1.1" 200 -
192.168.15.180 - - [07/Dec/2020 20:26:45] "GET /gameassets/Zwift_Updates_Root/Launcher_ver_cur.xml HTTP/1.1" 200 -
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:26:47] "GET /signup HTTP/1.1" 308 454 0.001682
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:26:47] "GET /signup/ HTTP/1.1" 200 3200 0.005123
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:26:52] "POST /signup/ HTTP/1.1" 302 563 0.053519
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:26:53] "GET /login/ HTTP/1.1" 200 3077 0.001586
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:26:59] "POST /login/ HTTP/1.1" 302 913 0.004408
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:26:59] "GET /user/t%40t.t/?enable_ghosts=True&online=%3Czwift_offline.Online+object+at+0x7fd1cd1237f0%3E HTTP/1.1" 200 3502 0.011781
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:27:01] "POST /start-zwift HTTP/1.1" 302 394 0.003241
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:27:01] "GET /ride HTTP/1.1" 302 4126 0.001604
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:27:01] "POST /auth/realms/zwift/protocol/openid-connect/token HTTP/1.1" 200 3807 0.058117
192.168.15.180 - - [07/Dec/2020 20:27:03] "GET /gameassets/MapSchedule_v2.xml HTTP/1.1" 200 -
192.168.15.180 - - [07/Dec/2020 20:27:09] "GET /gameassets/Streaming/Zwift_StreamingFiles_ver_cur.xml HTTP/1.1" 200 -
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:27:14] "GET /api/auth HTTP/1.1" 200 222 0.000769
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:27:14] "POST /auth/realms/zwift/protocol/openid-connect/token HTTP/1.1" 200 3807 0.001434
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:27:14] "POST /api/users/login HTTP/1.1" 200 253 0.000792
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:27:15] "GET /relay/worlds/hash-seeds HTTP/1.1" 200 199 0.001034
ERROR:zwift_offline:Exception on /api/profiles/me [GET]
Traceback (most recent call last):
  File "/opt/p38/lib64/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/p38/lib64/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/p38/lib64/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/p38/lib64/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/p38/lib64/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/p38/lib64/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/p38/zwift-offline/zwift_offline.py", line 315, in wrapper
    login_manager._load_user()
  File "/opt/p38/lib64/python3.8/site-packages/flask_login/login_manager.py", line 329, in _load_user
    user = self._load_user_from_remember_cookie(cookie)
  File "/opt/p38/lib64/python3.8/site-packages/flask_login/login_manager.py", line 366, in _load_user_from_remember_cookie
    user_id = decode_cookie(cookie)
  File "/opt/p38/lib64/python3.8/site-packages/flask_login/utils.py", line 57, in decode_cookie
    payload, digest = cookie.rsplit(u'|', 1)
AttributeError: 'NoneType' object has no attribute 'rsplit'
Exception: 'NoneType' object has no attribute 'rsplit'
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:27:15] "GET /api/profiles/me HTTP/1.1" 500 426 0.001738
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:27:15] "GET /api/telemetry/config HTTP/1.1" 200 135 0.001092
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:27:18] "POST /api/zfiles HTTP/1.1" 200 175 0.059338
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:27:18] "GET /api/zfiles/list?folder=logfiles HTTP/1.1" 200 115 0.000747
ERROR:zwift_offline:Exception on /api/profiles/0 [PUT]
Traceback (most recent call last):
  File "/opt/p38/lib64/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/p38/lib64/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/p38/lib64/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/p38/lib64/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/p38/lib64/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/p38/lib64/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/p38/zwift-offline/zwift_offline.py", line 315, in wrapper
    login_manager._load_user()
  File "/opt/p38/lib64/python3.8/site-packages/flask_login/login_manager.py", line 329, in _load_user
    user = self._load_user_from_remember_cookie(cookie)
  File "/opt/p38/lib64/python3.8/site-packages/flask_login/login_manager.py", line 366, in _load_user_from_remember_cookie
    user_id = decode_cookie(cookie)
  File "/opt/p38/lib64/python3.8/site-packages/flask_login/utils.py", line 57, in decode_cookie
    payload, digest = cookie.rsplit(u'|', 1)
AttributeError: 'NoneType' object has no attribute 'rsplit'
Exception: 'NoneType' object has no attribute 'rsplit'
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:27:18] "PUT /api/profiles/0?only-game-fields=true HTTP/1.1" 500 426 0.001895
ERROR:zwift_offline:Exception on /api/users/logout [POST]
Traceback (most recent call last):
  File "/opt/p38/lib64/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/p38/lib64/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/p38/lib64/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/p38/lib64/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/p38/lib64/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/p38/lib64/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/p38/zwift-offline/zwift_offline.py", line 315, in wrapper
    login_manager._load_user()
  File "/opt/p38/lib64/python3.8/site-packages/flask_login/login_manager.py", line 329, in _load_user
    user = self._load_user_from_remember_cookie(cookie)
  File "/opt/p38/lib64/python3.8/site-packages/flask_login/login_manager.py", line 366, in _load_user_from_remember_cookie
    user_id = decode_cookie(cookie)
  File "/opt/p38/lib64/python3.8/site-packages/flask_login/utils.py", line 57, in decode_cookie
    payload, digest = cookie.rsplit(u'|', 1)
AttributeError: 'NoneType' object has no attribute 'rsplit'
Exception: 'NoneType' object has no attribute 'rsplit'
INFO:zoffline:192.168.15.180 - - [2020-12-07 20:27:18] "POST /api/users/logout HTTP/1.1" 500 426 0.001724
192.168.15.180 - - [07/Dec/2020 20:27:19] "GET /gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml HTTP/1.1" 200 -
192.168.15.180 - - [07/Dec/2020 20:27:19] "GET /gameassets/Zwift_Updates_Root/Launcher_ver_cur.xml HTTP/1.1" 200 -
^CTraceback (most recent call last):
  File "standalone.py", line 149, in sigint_handler
    httpd.shutdown()
  File "/usr/lib64/python3.8/socketserver.py", line 252, in shutdown
    self.__is_shut_down.wait()
  File "src/gevent/event.py", line 159, in gevent._gevent_cevent.Event.wait
  File "src/gevent/_abstract_linkable.py", line 381, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 346, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 348, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 303, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 64, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 67, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
  File "src/gevent/_greenlet_primitives.py", line 68, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
gevent.exceptions.BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
2020-12-07T19:27:21Z
Exception ignored in: <module 'threading' from '/usr/lib64/python3.8/threading.py'>
Traceback (most recent call last):
  File "/opt/p38/lib64/python3.8/site-packages/gevent/monkey.py", line 886, in _shutdown
    orig_shutdown()
  File "/usr/lib64/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
  File "/opt/p38/lib64/python3.8/site-packages/gevent/thread.py", line 118, in acquire
    acquired = BoundedSemaphore.acquire(self, blocking, timeout)
  File "src/gevent/_semaphore.py", line 143, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src/gevent/_semaphore.py", line 178, in gevent._gevent_c_semaphore.Semaphore.acquire
  File "src/gevent/_abstract_linkable.py", line 381, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 346, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 348, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 303, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
  File "standalone.py", line 149, in sigint_handler
    httpd.shutdown()
  File "/usr/lib64/python3.8/socketserver.py", line 252, in shutdown
    self.__is_shut_down.wait()
  File "src/gevent/event.py", line 159, in gevent._gevent_cevent.Event.wait
  File "src/gevent/_abstract_linkable.py", line 381, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 346, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 348, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 303, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 64, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 67, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
  File "src/gevent/_greenlet_primitives.py", line 68, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
gevent.exceptions.BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
(p38) [root@minecraft zwift-offline]#
```
In case you need a tester with android please let me know. Also I can share with you the way how to install zwift (with custom CA) on non-rooted device if you are interested (but for hosts part this will require own dns server in your LAN).

**Comment by oldnapalm** [comment] 2020-12-07 19:56
Yes, the issue has no relation with session_protection (I edited my previous post).

Actually the problem happens when we use login_user(user, remember=False) ("remember me" unchecked).

Using tag zoffline_1.0.59353 works because the bug was introduced in a later commit
https://github.com/oldnapalm/zwift-offline/compare/zoffline_1.0.59353...master

You can try with master, just change line 371 to `login_user(user, remember=True)`. It will remember the session regardless of "remember me" being unchecked, but the issue should not occur.

**Comment by oldnapalm** [comment] 2020-12-08 14:26
The issue seems to be session_cookie is empty when we call login_user with remember=False.

I changed to remember user by default for now. Will look for a way to keep it as an option.

**Comment by oldnapalm** [comment] 2020-12-18 17:33
Addressed in https://github.com/oldnapalm/zwift-offline/commit/5465d4b6842346d51c7122414c839518f9cf6bd6

**Closed by oldnapalm** 2020-12-18 17:33 UTC
