### ISSUE TITLE
network error when buying a bike

### ISSUE THREAD

**Issue by flix56** [zoffline/zwift-offline#143] opened 2021-09-13 09:34 UTC
I can't buy a bike in the store, although a drop is enough

**Comment by oldnapalm** [comment] 2021-09-13 23:47
I can't reproduce this error, can you give more details?

**Comment by flix56** [comment] 2021-09-14 10:47
> Я не могу воспроизвести эту ошибку, не могли бы вы рассказать подробнее?

I went to the profile where 50 lvl and a lot of money, I wanted to buy a bike for 800,000 and I have 100,000,000 drops, but when I click buy, the network error writes and does not allow me to buy it, what do you say to do?

**Comment by flix56** [comment] 2021-09-14 14:42
> Где появляется сообщение об ошибке? Пожалуйста, опубликуйте скриншот.
![image](https://user-images.githubusercontent.com/90610196/133279092-5ccead9f-376c-44ce-90ca-fd57c1005eb1.png)
![zwift](https://user-images.githubusercontent.com/90610196/133279122-278659ab-d450-4549-93b3-9384232b31ae.jpg)

**Comment by flix56** [comment] 2021-09-14 19:11
I will try it through my account and in a month I will tell you what happened

**Comment by oldnapalm** [comment] 2021-09-14 19:29
Post zoffline log after trying to buy the bike (what appears in the command prompt window).

**Comment by flix56** [comment] 2021-09-14 19:30
Okay I'll send you a photo tomorrow

**Comment by flix56** [comment] 2021-09-15 12:01
![image](https://user-images.githubusercontent.com/90610196/133429568-4af1912f-adea-4d44-8eb9-b9d33e8c0e3d.png)

**Comment by oldnapalm** [comment] 2021-09-15 12:35
Looks like zoffline can't write to profile.bin, I think it may be due to the Cyrillic letters in the path (not sure how it can read the file though). Could you try to move zoffline folder to a path without Cyrillic letters, just to confirm if it's the problem or not?

**Comment by flix56** [comment] 2021-09-15 13:07
![image](https://user-images.githubusercontent.com/90610196/133438885-7099d7c1-3bef-4ed7-9168-b41f5e82dfc0.png)
nothing has changed

**Comment by oldnapalm** [comment] 2021-09-15 13:19
Please check if the file profile.bin is really in the folder `storage/1` and if it's not read-only.

Did you run zoffline before copying the level 50 profile over?

**Comment by oldnapalm** [comment] 2021-09-15 14:25
I think the issue may be due to double backslash in path. Is D: a SMB connection to a remote server?

https://stackoverflow.com/questions/22567785/error-with-double-backslash-in-windows-path-in-python

**Comment by flix56** [comment] 2021-09-15 15:35
yes

**Comment by oldnapalm** [comment] 2021-09-15 15:50
Then try moving zoffline to a local filesystem.

**Comment by oldnapalm** [comment] 2021-09-15 16:09
If moving to local filesystem works and you are running from source, try changing line 67 of zwift_offline.py to `STORAGE_DIR = os.path.join(SCRIPT_DIR, "storage")`

**Comment by flix56** [comment] 2021-09-15 16:19
what does a local file system mean, and yes, I first created my account only then set the accanut of level 50

**Comment by flix56** [comment] 2021-09-15 16:35
I solved the problem, the profile was in another place, thank you for your help

**Comment by oldnapalm** [comment] 2021-09-15 16:36
When you answered "yes" after I ask "Is D: a SMB connection to a remote server?", that answer was not to my last question?

A local filesystem is a drive letter which is not mapped to a network drive. If D: is not a SMB connection, then I don't understand why it uses double backslash (D:\\zoffline)

The only think I can suggest for now is in my previous answer, change line 67 of zwift_offline.py to `STORAGE_DIR = os.path.join(SCRIPT_DIR, "storage")`

**Comment by oldnapalm** [comment] 2021-09-15 17:45
Can you please make clear if it's a network filesystem issue or it was your mistake?

If it's a network issue I can look for a fix, or else you can close the issue.

**Comment by flix56** [comment] 2021-09-15 19:08
it was a problem in the file name, I needed it to be called /1 and it was /25674, I changed and fixed the situation

**Closed** 2021-09-15 19:12 UTC
