### ISSUE TITLE
Level 60-100 issue

### ISSUE THREAD

**Issue by jricoclq** [zoffline/zwift-offline#300] opened 2024-01-05 08:23 UTC
hi,
It seems that when the level reaches 60, experience points will not increase.
![image](https://github.com/zoffline/zwift-offline/assets/102775665/d4d8e866-9adc-44e0-a453-2f7165381409)

**Comment by stapa** [comment] 2024-01-05 08:30
related to #295

**Comment by oldnapalm** [comment] 2024-01-05 13:35
Duplicate of #295

**Closed by oldnapalm** 2024-01-05 13:35 UTC
