### ISSUE TITLE
Android (non-rooted device)

### ISSUE THREAD

**Issue by r4zi3lrrr** [zoffline/zwift-offline#148] opened 2021-09-29 20:58 UTC
Hi,

None of the links for Android (non-rooted device) work is that intentional?

Thank you.

**Comment by oldnapalm** [comment] 2021-09-30 22:15
Hi,

I think @Argon2000 updated https://github.com/Argon2000/ZofflineObbAndroid/ and forgot to update the apk link. For now you can download zoffline-obb.apk from [here](https://drive.google.com/drive/folders/1fl0U3FXEIKu_Q61Db_C9tttlqDBpNW7M?usp=sharing).

Regarding "Host Changer VPN - The Game Changer", looks like it was removed from Google Play. I don't use Zwift on Android, but I would try an alternative like https://play.google.com/store/apps/details?id=dns.hosts.server.change

**Comment by Argon2000** [comment] 2021-09-30 22:19
Please note that the certificate used in the new ZofflineObb app is the one from the 'online' server. @oldnapalm can probably point you too that zoffline release

**Comment by oldnapalm** [comment] 2021-09-30 22:39
@Argon2000

The version with the new certificate is not being maintained since it's no longer required for the `/v1/variant` route. The feature was merged into master and uses the default zoffline certificate now, so it would be nice if you could release a zoffline-obb.apk with the original certificate. Maybe the old one still works?

@r4zi3lrrr

I guess you can try this version instead of the Google Drive link from my previous reply
https://github.com/Argon2000/ZofflineObbAndroid/tree/88096ef6702245b4bd63558380c94d9b6657cb01/app/release

**Comment by Argon2000** [comment] 2021-09-30 22:41
Okay, I'll try and update it tomorrow.

**Comment by Argon2000** [comment] 2021-10-01 07:48
Posted a new release on my github for the Android app: https://github.com/Argon2000/ZofflineObbAndroid/releases/tag/v1.1
Instructions also added in a Readme there.

**Comment by r4zi3lrrr** [comment] 2021-10-01 16:21
Thanks for providing new links. 

I'm trying to install the  Apk file and getting a "Parse error" any ideas if the Apk file works and which version of Android o/s it was created for?

**Comment by oldnapalm** [comment] 2021-10-01 16:38
Did you allow installation from unknown sources?

**Comment by r4zi3lrrr** [comment] 2021-10-01 16:46
Yup

**Comment by Argon2000** [comment] 2021-10-01 17:20
Android 11 is what I've tested it on

**Comment by r4zi3lrrr** [comment] 2021-12-31 15:39
I've tested this on Android 9 but doesn't seem to work for me.

Created  host file on tablet as:

<192.168.1.228> us-or-rly101.zwift.com
<192.168.1.228> secure.zwift.com
<192.168.1.228> cdn.zwift.com

Have run ZofflineObb.

I have zoffline running on a windows laptop (just says INFO:zoffline:Server is running)  but there's no indication of connection within the zoffline window, also zswift running on tablet has the standard 25km left.

I can ping my IP: 192.168.1.228 from the tablet.

Any ideas please?

**Comment by oldnapalm** [comment] 2021-12-31 15:46
Remove the < > surrounding the IP, it should be
```
192.168.1.228 us-or-rly101.zwift.com
192.168.1.228 secure.zwift.com
192.168.1.228 cdn.zwift.com
```

**Comment by r4zi3lrrr** [comment] 2021-12-31 16:05
Tried that - still no joy.

**Comment by oldnapalm** [comment] 2021-12-31 16:41
- Check if Host Changer is enabled
- Check if zoffline is allowed in Windows firewall

You should be able to access http://192.168.1.228/gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml (or http://cdn.zwift.com/gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml) from your browser on tablet.

**Comment by r4zi3lrrr** [comment] 2021-12-31 17:27
Firewall was already turned off.
Host changer definitely switched on.

Can't access both links properly: 

http://192.168.1.228/gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml - Site can't be reached.

http://cdn.zwift.com/gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml - This XML file does not appear to have any style information associated with it.

**Comment by oldnapalm** [comment] 2021-12-31 17:35
> http://192.168.1.228/gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml - Site can't be reached.

If the IP is correct and zoffline is allowed in firewall, really no idea.

Can you access the same address from Windows browser?

> http://cdn.zwift.com/gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml - This XML file does not appear to have any style information associated with it.

This means you are accessing the file on retail server (Host Changer is not working for some reason). Did you restart it after removing the < > from IP?

**Comment by r4zi3lrrr** [comment] 2021-12-31 18:12
Can't access those url's from my windows machine either. :(

I did turn Host Changer on/off but just restarted the tablet and got the same issue as per below.

Just wondering if my version of Zswift is too new, it's version 1.20.1 (100278) and the version of zoffline I have is 1.0.100278.

Just checked zoffline again and saw this:

INFO:zoffline:Server is running.
192.168.1.137 - - [31/Dec/2021 18:02:39] "GET /gameassets/Zwift_Updates_Roo
ft_ver_cur.xml HTTP/1.1" 200 -
192.168.1.137 - - [31/Dec/2021 18:02:39] code 404, message File not found
192.168.1.137 - - [31/Dec/2021 18:02:39] "GET /favicon.ico HTTP/1.1" 404 -
192.168.1.228 - - [31/Dec/2021 18:04:37] "GET /gameassets/Zwift_Updates_Roo
ft_ver_cur.xml HTTP/1.1" 200 -
192.168.1.228 - - [31/Dec/2021 18:04:37] code 404, message File not found
192.168.1.228 - - [31/Dec/2021 18:04:37] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by oldnapalm** [comment] 2021-12-31 18:47
The Zwift and zoffline versions match, that's not the problem.

If you see those messages in zoffline, it means that your browser can access it, both from 192.168.1.137 (tablet?) and 192.168.1.228 (Windows). The error 404 from favicon.ico is expected.

Your issue seems to be with Host Changer, for some reason it's not translating the host names to the IP as configured in hosts.txt. Try to review the installation steps.

**Comment by oldnapalm** [comment] 2022-01-01 12:27
Make sure you launch and enable Host Changes **before** launching Zwift.

I never used Zwift on Android, but on Windows, if you edit hosts after launching Zwift (with the launcher icon already present in system tray, even if launcher window is closed) the hosts change won't take effect.

**Comment by Argon2000** [comment] 2022-01-02 09:14
And there can also be some delay after switching it on before the traffic is actually redirected. Make sure Zwift is not running in the background when turning host changer on. Then you can also verify you can browser to the launcher before launching Zwift (from Firefox)

**Comment by oldnapalm** [comment] 2022-01-18 16:35
Closing due to inactivity.

**Closed by oldnapalm** 2022-01-18 16:35 UTC

**Comment by r4zi3lrrr** [comment] 2022-01-18 19:59
Apologies for not replying earlier had an issue with the charger on my tablet.
Will probably give this try on the weekend.
Thanks for the support guys.

**Comment by tapirashabrack** [comment] 2024-04-01 08:37
Hi everyone, 

I ran into the exact same problem recently, and that thread has been very helpful to me. It's one of the first results I got from google typing "zwift offline android". I eventually found a way out I'd like to share even if this thread has been closed for more than two years.

My configuration :
- one laptop Win10 R2H2 + zoffline_1.0.127957 server. Local IP : 192.168.1.13
- one smartphone Samsung S23 Android 14 OneUI 6.1 + zwift client 1.0.127903 (from playstore)

What primarily worked : zoffline server + zwift client running on the same win10 laptop
What didn't work : zoffline server running on the win10 laptop + zwift client running on android 14 smartphone

What is causing the problem :
- Virtual Host is not working. I had no problem to install it or run it, it's simply not doing what it is supposed to do
- Assigning the local IP of the win10 laptop (192.168.1.13) to the smartphone wifi settings DNS1 is not working either
Please note that I followed the readme thoroughly and did many tests / change in settings before coming to this conclusion

How to confirm it's not working :
- method 1) as stated above in the thread :
	- launch zoffline server on the laptop
	- open a web browser on the smartphone, and try to access http://cdn.zwift.com/gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml 
	- if no new text message is displayed in the zoffline server console, then it means the HTTP request has not been routed to the laptop local IP as it should be
	- why it's not the best method IMHO : it's not explicit enough.
- method 2) which I recommend because it is more explicit : 
	- install JuiceSSH on your smartphone (https://play.google.com/store/apps/details?id=com.sonelli.juicessh&hl=fr&gl=US&pli=1)
	- activate Virtual Hosts, or use whatever method described in the readme (smartphone Wifi DNS1...)
	- launch JuiceSSH and make a ping request (tutos on YT) to one of the Zwift server DNS : us-or-rly101.zwift.com OR secure.zwift.com OR cdn.zwift.com
	- check the destination IP. If it's not zoffline server local IP (192.168.1.13 in my case), then Virtual Hosts or alternate method is not working

How I made it work :

Well I didn't found a free solution for that. It happened I was paying for a VPN service (Windscribe) for various other reasons, and it can block specific DNS adresses or do IP spoofing through custom rules. I only had to make three rules as below. 
Now I only need to start the VPN service on my smartphone before I launch Zwift client and everything works properly.


![robert](https://github.com/zoffline/zwift-offline/assets/165645017/4537311a-2d9c-48bf-beb3-008d38f43184)


I didn't look for a free solution available on the playstore, but I hope someone can.

Best regards, TapiraShabrack

**Comment by jvu001** [comment] 2024-09-14 20:20
@tapirashabrack, thank you for this very detailed writeup! I had to search multiple times to finally get to this post.

I have to confirm that I'm getting the same results you are. 

Method 1: Windows zwift offline server, and windows zwift client WORKS (when editing native hosts file in the windows box)
Method 2: Windows zwift offline server, and Android (non-root) zwift client FAILS
Method 3: Linux zwift offline server on laptop, and Android (non-root) zwift client FAILS

It appears that the problem is the Virtual Hosts app. If you go to Virtual Hosts github there are numerous ticket requests to make it work on Android 13 or 14. I suspect that your Android device is running either Android 13 or 14.

I've tested multiple Android devices, all Android 14 unfortunately and none of them are routing DNS through Virtual Hosts. Other tests I've done in addition to yours: turned off mobile data and only routed through wifi. Changed the android device's ip to static IP and only had one entry for the DNS1 to be the local zwift offline server's IP. And it STILL routed DNS through my access point to the internet! I don't know why this is a considered a more secure option for Android 13/14!

I suspect that it won't work unless you root your Android device and edit the native /etc/hosts file to match the local zwift offline server, if you wish to run Android 13/14.  Unfortunately I do not feel rooting the device will do me any good--extra work and likely will stop all future (security) update.

If anyone has access to an older Android device (pre-Android 13), could you confirm if Virtual Hosts is running in your device? Thank you!

**Comment by fatsbrown** [comment] 2024-09-14 20:51
@jvu001

Virtual Hosts is working for me on Android 13 (Samsung Galaxy S20), I just need to do what's mentioned in readme, after selecting hosts.txt, fully close (touch the "overview" button and swipe up) the app and run it again. If I simply select the hosts file and run Zwift (or Companion), redirection doesn't work.

The FakeDNS method works too, but I need to set both DNS 1 and 2 to the zoffline IP, if I set only DNS 1 it doesn't work.

**Comment by jvu001** [comment] 2024-09-14 23:54
@fatsbrown 

Thank you for letting me know Android 13 is working for you. I did do exactly as the readme said, select hosts.txt, fully close and then run again but did not work.

As to setting both DNS 1 and 2 to the zoffline server IP, I will have to try that and will post here. Thank you for the suggestion.

**Comment by daktak** [comment] 2024-09-16 01:20
Virtual hosts works for me if i enable airplane mode (and turn wifi back on)

**Comment by fatsbrown** [comment] 2024-10-10 17:50
@jvu001 a hint from another Android 14 user (#373), disabling "private DNS" made it work.
